# Generated by Django 3.2.3 on 2021-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjc', '0002_rename_titile_events_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='invite_link',
            field=models.CharField(default='nolink', max_length=200),
            preserve_default=False,
        ),
    ]
