# Generated by Django 3.2.3 on 2021-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjc', '0003_events_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_loc',
            field=models.CharField(default='adimaly', max_length=200),
            preserve_default=False,
        ),
    ]
